service:
  name: Blog project
  description: Blog project service to manage users, posts, blogs,...
  baseUrl: /api/v1
  apiVersion: 0.1.0
  docsBaseUrl: /api/docs


serviceAuthentication:
    username: admin
    password: admin

server:
  port: 3000
  swaggerSchema: http
  hostname: localhost
  cors:
    allowedHeaders: 'authorization,content-type'
    exposedHeaders: 'authorization,x-pagination-page,x-pagination-page-size,x-pagination-total'

db:
  mongodb:
    uri: mongodb://localhost:27017/blog-project

logger:
  formatter: local-custom
  fieldsToMask:
    - accessToken

jwt:
  scretKey: sample-secret-key